### PR TITLE
integrated mongodb database into the project

### PR DESCRIPTION
**Pull request by janmesh799**

### CODE REVIEW

**Review by mog-rn — COMMENTED** [review]
@janmesh799 thanks for your efforts.
1. I wanted to know if I switch to MongoDB Atlas will it be a smooth process or?
2. And I wanted to add typescript support to the project will it interfere with how you've written your code 
3. Will you be taking another issue to work on after this?

**Comment by janmesh799** [comment]
1. yes switching to MongoDb Atlas will be smooth process.
2.  frankly speaking i don't have that much idea of TS , that i can answer this question
3.  I can take issues related to backend, but for frontend i have exprience in ReactJs, i don't have any experience in NextJs

**Comment by Mogakamo** [comment]
you can text me on discord via mogaka_dev#3773 so that we can discuss further

**Review by mog-rn — APPROVED** [review]

**Comment by janmesh799** [comment]
can you put a label of hacktober on this pr and issue

**Pull request merged**
